### ISSUE TITLE
docker pull from ghcr fails as unauthorized

### ISSUE THREAD

**Issue by michquinn** [agile-learning-institute/mentorHub-search-opensearch#13]
```bash
Error response from daemon: Head "https://ghcr.io/v2/agile-learning-institute/mentorhub-search-searchinit/manifests/latest": unauthorized
```
Is this image public?

**Comment by MyNameIsAndrew-Mangix** [comment]
It should be. `mh up search-db` works is working on my end after I updated. It got merged 10 minutes after you made the issue.

**Comment by michquinn** [comment]
Still running into it

For reference: https://niklasmtj.de/blog/gh-actions-workflows-combination-with-ghcr/

**Comment by MyNameIsAndrew-Mangix** [comment]
The image wasn't public, Mike made it public so it should be fixed

**Comment by michquinn** [comment]
That seems to have worked, thanks
